In [2]:
from read_conllu import test_annotation
from spacy_conllu import spacy_to_conll, clean_text
import spacy

nlp = spacy.load("ca_core_news_trf")
nlp.add_pipe("conll_formatter",config={"include_headers": True}, last=True)
doc1=nlp(clean_text("El pressupost del projecte és de 192.558.751 pta., dels quals 96.279.375 són finançats per l'ACA, i la resta ho finança l'Ajuntament tenint en compte que 38.750.000 pta. provenen del PUOiS.".lower()))
doc2=nlp("El pressupost del projecte és de 192.558.751 pta., dels quals 96.279.375 són finançats per l'ACA, i la resta ho finança l'Ajuntament tenint en compte que 38.750.000 pta. provenen del PUOiS.")

print("unala")
print(doc1._.conll_str)
print(doc2._.conll_str)

/home/pessa/PycharmProjects/ForestFrontiers/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

unala
# sent_id = 1
# text = el pressupost del projecte és de 192.558.751 pta
1	el	el	DET	DET	Definite=Def|Gender=Masc|Number=Sing|PronType=Art	2	det	_	_
2	pressupost	pressupost	NOUN	NOUN	Gender=Masc|Number=Sing	9	nsubj	_	_
3	d	de	ADP	ADP	_	5	case	_	SpaceAfter=No
4	el	el	DET	DET	Definite=Def|Gender=Masc|Number=Sing|PronType=Art	5	det	_	_
5	projecte	projecte	NOUN	NOUN	Gender=Masc|Number=Sing	2	nmod	_	_
6	és	ser	AUX	AUX	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	9	cop	_	_
7	de	de	ADP	ADP	_	9	case	_	_
8	192.558.751	192.558.751	NUM	NUM	NumForm=Digit|NumType=Card	9	nummod	_	_
9	pta	pta	NOUN	NOUN	NumForm=Digit	0	ROOT	_	SpaceAfter=No

# sent_id = 2
# text = ., dels quals 96.279.375 són finançats per l'aca, i la resta ho finança l'ajuntament tenint en compte que 38.750.000 pta. provenen del puois
1	.	.	NOUN	NOUN	NumForm=Digit	0	ROOT	_	SpaceAfter=No
2	,	,	PUNCT	PUNCT	PunctType=Comm	8	punct	_	_
3	d	de	ADP	ADP	_	5	case	_	SpaceAfter=No
4	els	el	DET	DET	Definite=Def|Gender=Masc|Number=Plur|PronType=Art	5	det	_	_
5	quals	qual	PRON	PRON	Number=Plur|PronType=Rel	8	obj	_	_
6	96.279.375	96.279.375	NUM	NUM	NumForm=Digit|NumType=Card	8	nsubj	_	_
7	són	ser	AUX	AUX	Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin	8	aux	_	_
8	finançats	finançar	VERB	VERB	Gender=Masc|Number=Plur|Tense=Past|VerbForm=Part	1	acl	_	_
9	per	per	ADP	ADP	_	11	case	_	_
10	l'	el	DET	DET	Definite=Def|Number=Sing|PronType=Art	11	det	_	SpaceAfter=No
11	aca	aca	PROPN	PROPN	_	8	obj	_	SpaceAfter=No
12	,	,	PUNCT	PUNCT	PunctType=Comm	17	punct	_	_
13	i	i	CCONJ	CCONJ	_	17	cc	_	_
14	la	el	DET	DET	Definite=Def|Gender=Fem|Number=Sing|PronType=Art	15	det	_	_
15	resta	resta	NOUN	NOUN	Gender=Fem|Number=Sing	17	obj	_	_
16	ho	ho	PRON	PRON	Case=Acc|Gender=Neut|Number=Sing|Person=3|PronType=Prs	17	obj	_	_
17	finança	finançar	VERB	VERB	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	8	conj	_	_
18	l'	el	DET	DET	Definite=Def|Number=Sing|PronType=Art	19	det	_	SpaceAfter=No
19	ajuntament	ajuntament	NOUN	NOUN	Gender=Masc|Number=Sing	17	nsubj	_	_
20	tenint	tenir	VERB	VERB	VerbForm=Ger	17	advcl	_	_
21	en	en	ADP	ADP	_	22	case	_	_
22	compte	compte	NOUN	NOUN	Number=Sing	20	compound	_	_
23	que	que	SCONJ	SCONJ	_	27	mark	_	_
24	38.750.000	38.750.000	NUM	NUM	NumForm=Digit|NumType=Card	25	nummod	_	_
25	pta	pta	NOUN	NOUN	NumForm=Digit	27	nsubj	_	SpaceAfter=No
26	.	.	NOUN	NOUN	NumForm=Digit	27	nsubj	_	_
27	provenen	provenar	VERB	VERB	Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin	20	ccomp	_	_
28	d	de	ADP	ADP	_	30	case	_	SpaceAfter=No
29	el	el	DET	DET	Definite=Def|Gender=Masc|Number=Sing|PronType=Art	30	det	_	_
30	puois	puois	PROPN	PROPN	_	8	obj	_	SpaceAfter=No

# sent_id = 3
# text = .
1	.	.	PUNCT	PUNCT	PunctType=Peri	0	ROOT	_	SpaceAfter=No

# sent_id = 1
# text = El pressupost del projecte és de 192.558.751 pta
1	El	el	DET	DET	Definite=Def|Gender=Masc|Number=Sing|PronType=Art	2	det	_	_
2	pressupost	pressupost	NOUN	NOUN	Gender=Masc|Number=Sing	9	nsubj	_	_
3	d	de	ADP	ADP	_	5	case	_	SpaceAfter=No
4	el	el	DET	DET	Definite=Def|Gender=Masc|Number=Sing|PronType=Art	5	det	_	_
5	projecte	projecte	NOUN	NOUN	Gender=Masc|Number=Sing	2	nmod	_	_
6	és	ser	AUX	AUX	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	9	cop	_	_
7	de	de	ADP	ADP	_	9	case	_	_
8	192.558.751	192.558.751	NUM	NUM	NumForm=Digit|NumType=Card	9	nummod	_	_
9	pta	pta	NOUN	NOUN	NumForm=Digit	0	ROOT	_	SpaceAfter=No

# sent_id = 2
# text = ., dels quals 96.279.375 són finançats per l'ACA, i la resta ho finança l'Ajuntament tenint en compte que 38.750.000 pta. provenen del PUOiS.
1	.	.	NOUN	NOUN	NumForm=Digit	0	ROOT	_	SpaceAfter=No
2	,	,	PUNCT	PUNCT	PunctType=Comm	8	punct	_	_
3	d	de	ADP	ADP	_	5	case	_	SpaceAfter=No
4	els	el	DET	DET	Definite=Def|Gender=Masc|Number=Plur|PronType=Art	5	det	_	_
5	quals	qual	PRON	PRON	Number=Plur|PronType=Rel	8	obj	_	_
6	96.279.375	96.279.375	NUM	NUM	NumForm=Digit|NumType=Card	8	nsubj	_	_
7	són	ser	AUX	AUX	Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin	8	aux	_	_
8	finançats	finançar	VERB	VERB	Gender=Masc|Number=Plur|Tense=Past|VerbForm=Part	1	acl	_	_
9	per	per	ADP	ADP	_	11	case	_	_
10	l'	el	DET	DET	Definite=Def|Number=Sing|PronType=Art	11	det	_	SpaceAfter=No
11	ACA	ACA	PROPN	PROPN	_	8	obj	_	SpaceAfter=No
12	,	,	PUNCT	PUNCT	PunctType=Comm	17	punct	_	_
13	i	i	CCONJ	CCONJ	_	17	cc	_	_
14	la	el	DET	DET	Definite=Def|Gender=Fem|Number=Sing|PronType=Art	15	det	_	_
15	resta	resta	NOUN	NOUN	Gender=Fem|Number=Sing	17	obj	_	_
16	ho	ho	PRON	PRON	Case=Acc|Gender=Neut|Number=Sing|Person=3|PronType=Prs	17	obj	_	_
17	finança	finançar	VERB	VERB	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	8	conj	_	_
18	l'	el	DET	DET	Definite=Def|Number=Sing|PronType=Art	19	det	_	SpaceAfter=No
19	Ajuntament	Ajuntament	PROPN	PROPN	_	17	nsubj	_	_
20	tenint	tenir	VERB	VERB	VerbForm=Ger	17	advcl	_	_
21	en	en	ADP	ADP	_	22	case	_	_
22	compte	compte	NOUN	NOUN	Number=Sing	20	compound	_	_
23	que	que	SCONJ	SCONJ	_	27	mark	_	_
24	38.750.000	38.750.000	NUM	NUM	NumForm=Digit|NumType=Card	25	nummod	_	_
25	pta	pta	NOUN	NOUN	NumForm=Digit	27	nsubj	_	SpaceAfter=No
26	.	.	NOUN	NOUN	NumForm=Digit	27	nsubj	_	_
27	provenen	provenar	VERB	VERB	Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin	20	ccomp	_	_
28	d	de	ADP	ADP	_	30	case	_	SpaceAfter=No
29	el	el	DET	DET	Definite=Def|Gender=Masc|Number=Sing|PronType=Art	30	det	_	_
30	PUOiS.	PUOiS.	PROPN	PROPN	_	8	obl	_	SpaceAfter=No

In [15]:
from read_conllu import test_annotation
llista_atr_curta=["lemma", "upos", "head", "deprel"]
d_err= dict()
for i in llista_atr_curta:
    d_i= test_annotation("ca_ancora-ud-train.conllu","500_ca_spacy.conllu",  257, i, printf= False)
    print(i)
    for key in d_i.keys():
        print(key, d_i[key])
        if key not in d_err:
            d_err[key] = d_i[key]
        else:
            print("FLAG")
            d_err[key].update(d_i[key])

    #     if
    # if d_i["id"] in d_err:
    #     d_err[d_i["id"]]= d_err[d_i["id"]].update(d_i)
    # else:
    #     d_err[d_i["id"]] = d_i

print(d_err)

lemma
1_48 {'id': '1_48', 'sentence_id': '1', 'tok_id': '48', 'lemma error': True, 'form1': 'càrniques', 'form2': 'càrniques', 'rightlemma': 'càrnic', 'wronglemma': 'càrniqu'}
3_14 {'id': '3_14', 'sentence_id': '3', 'tok_id': '14', 'lemma error': True, 'form1': 'càrniques', 'form2': 'càrniques', 'rightlemma': 'càrnic', 'wronglemma': 'càrniqu'}
3_16 {'id': '3_16', 'sentence_id': '3', 'tok_id': '16', 'lemma error': True, 'form1': 'La', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
4_12 {'id': '4_12', 'sentence_id': '4', 'tok_id': '12', 'lemma error': True, 'form1': 'una', 'form2': 'una', 'rightlemma': 'un', 'wronglemma': 'una'}
7_15 {'id': '7_15', 'sentence_id': '7', 'tok_id': '15', 'lemma error': True, 'form1': 'desconeguessin', 'form2': 'desconeguessin', 'rightlemma': 'desconèixer', 'wronglemma': 'desconeguar'}
8_6 {'id': '8_6', 'sentence_id': '8', 'tok_id': '6', 'lemma error': True, 'form1': 'Fomento', 'form2': 'fomento', 'rightlemma': 'Fomento', 'wronglemma': 'fomentar'}
12_15 {'id': '12_15', 'sentence_id': '12', 'tok_id': '15', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
15_11 {'id': '15_11', 'sentence_id': '15', 'tok_id': '11', 'lemma error': True, 'form1': 'Relacions', 'form2': 'relacions', 'rightlemma': 'Relacions', 'wronglemma': 'relació'}
15_12 {'id': '15_12', 'sentence_id': '15', 'tok_id': '12', 'lemma error': True, 'form1': 'Laborals', 'form2': 'laborals', 'rightlemma': 'Laborals', 'wronglemma': 'laboral'}
15_27 {'id': '15_27', 'sentence_id': '15', 'tok_id': '27', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
16_19 {'id': '16_19', 'sentence_id': '16', 'tok_id': '19', 'lemma error': True, 'form1': 'la', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
16_34 {'id': '16_34', 'sentence_id': '16', 'tok_id': '34', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
18_8 {'id': '18_8', 'sentence_id': '18', 'tok_id': '8', 'lemma error': True, 'form1': 'una', 'form2': 'una', 'rightlemma': 'un', 'wronglemma': 'una'}
19_5 {'id': '19_5', 'sentence_id': '19', 'tok_id': '5', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
19_17 {'id': '19_17', 'sentence_id': '19', 'tok_id': '17', 'lemma error': True, 'form1': 'acumulin', 'form2': 'acumulin', 'rightlemma': 'acumular', 'wronglemma': 'acumulir'}
20_3 {'id': '20_3', 'sentence_id': '20', 'tok_id': '3', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
21_37 {'id': '21_37', 'sentence_id': '21', 'tok_id': '37', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
27_13 {'id': '27_13', 'sentence_id': '27', 'tok_id': '13', 'lemma error': True, 'form1': 'Tributària', 'form2': 'tributària', 'rightlemma': 'Tributària', 'wronglemma': 'tributari'}
32_18 {'id': '32_18', 'sentence_id': '32', 'tok_id': '18', 'lemma error': True, 'form1': 'una', 'form2': 'una', 'rightlemma': 'un', 'wronglemma': 'una'}
32_30 {'id': '32_30', 'sentence_id': '32', 'tok_id': '30', 'lemma error': True, 'form1': 'és', 'form2': 'és', 'rightlemma': 'és', 'wronglemma': 'ser'}
34_12 {'id': '34_12', 'sentence_id': '34', 'tok_id': '12', 'lemma error': True, 'form1': 'ho', 'form2': 'ho', 'rightlemma': 'ell', 'wronglemma': 'ho'}
34_20 {'id': '34_20', 'sentence_id': '34', 'tok_id': '20', 'lemma error': True, 'form1': 'ens', 'form2': 'ens', 'rightlemma': 'jo', 'wronglemma': 'nos'}
37_15 {'id': '37_15', 'sentence_id': '37', 'tok_id': '15', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
37_29 {'id': '37_29', 'sentence_id': '37', 'tok_id': '29', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
37_30 {'id': '37_30', 'sentence_id': '37', 'tok_id': '30', 'lemma error': True, 'form1': 'preveuen', 'form2': 'preveuen', 'rightlemma': 'preveure', 'wronglemma': 'preveuar'}
38_23 {'id': '38_23', 'sentence_id': '38', 'tok_id': '23', 'lemma error': True, 'form1': 'propietària', 'form2': 'propietària', 'rightlemma': 'propietari', 'wronglemma': 'propietàri'}
43_55 {'id': '43_55', 'sentence_id': '43', 'tok_id': '55', 'lemma error': True, 'form1': 'amenacin', 'form2': 'amenacin', 'rightlemma': 'amenaçar', 'wronglemma': 'amenacir'}
44_24 {'id': '44_24', 'sentence_id': '44', 'tok_id': '24', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
49_33 {'id': '49_33', 'sentence_id': '49', 'tok_id': '33', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
50_31 {'id': '50_31', 'sentence_id': '50', 'tok_id': '31', 'lemma error': True, 'form1': 'congressos', 'form2': 'congressos', 'rightlemma': 'congrés', 'wronglemma': 'congresso'}
51_16 {'id': '51_16', 'sentence_id': '51', 'tok_id': '16', 'lemma error': True, 'form1': 'rebi', 'form2': 'rebi', 'rightlemma': 'rebre', 'wronglemma': 'rebar'}
52_37 {'id': '52_37', 'sentence_id': '52', 'tok_id': '37', 'lemma error': True, 'form1': 'congressos', 'form2': 'congressos', 'rightlemma': 'congrés', 'wronglemma': 'congresso'}
53_4 {'id': '53_4', 'sentence_id': '53', 'tok_id': '4', 'lemma error': True, 'form1': 'provenen', 'form2': 'provenen', 'rightlemma': 'provenir', 'wronglemma': 'provenar'}
53_13 {'id': '53_13', 'sentence_id': '53', 'tok_id': '13', 'lemma error': True, 'form1': 'una', 'form2': 'una', 'rightlemma': 'un', 'wronglemma': 'una'}
53_28 {'id': '53_28', 'sentence_id': '53', 'tok_id': '28', 'lemma error': True, 'form1': 'Escaldes', 'form2': 'escaldes', 'rightlemma': 'Escaldes', 'wronglemma': 'escaldar'}
54_23 {'id': '54_23', 'sentence_id': '54', 'tok_id': '23', 'lemma error': True, 'form1': 'Socioculturals', 'form2': 'socioculturals', 'rightlemma': 'Socioculturals', 'wronglemma': 'sociocultural'}
55_3 {'id': '55_3', 'sentence_id': '55', 'tok_id': '3', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
55_14 {'id': '55_14', 'sentence_id': '55', 'tok_id': '14', 'lemma error': True, 'form1': 'pretenen', 'form2': 'pretenen', 'rightlemma': 'pretendre', 'wronglemma': 'pretenar'}
56_15 {'id': '56_15', 'sentence_id': '56', 'tok_id': '15', 'lemma error': True, 'form1': 'rebi', 'form2': 'rebi', 'rightlemma': 'rebre', 'wronglemma': 'rebar'}
60_4 {'id': '60_4', 'sentence_id': '60', 'tok_id': '4', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
60_26 {'id': '60_26', 'sentence_id': '60', 'tok_id': '26', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
60_27 {'id': '60_27', 'sentence_id': '60', 'tok_id': '27', 'lemma error': True, 'form1': 'busquin', 'form2': 'busquin', 'rightlemma': 'buscar', 'wronglemma': 'busquir'}
62_10 {'id': '62_10', 'sentence_id': '62', 'tok_id': '10', 'lemma error': True, 'form1': 'processos', 'form2': 'processos', 'rightlemma': 'procés', 'wronglemma': 'processo'}
63_16 {'id': '63_16', 'sentence_id': '63', 'tok_id': '16', 'lemma error': True, 'form1': 'processos', 'form2': 'processos', 'rightlemma': 'procés', 'wronglemma': 'processo'}
63_40 {'id': '63_40', 'sentence_id': '63', 'tok_id': '40', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
63_41 {'id': '63_41', 'sentence_id': '63', 'tok_id': '41', 'lemma error': True, 'form1': 'queixin', 'form2': 'queixin', 'rightlemma': 'queixar-se', 'wronglemma': 'queixir'}
63_44 {'id': '63_44', 'sentence_id': '63', 'tok_id': '44', 'lemma error': True, 'form1': 'llargues', 'form2': 'llargues', 'rightlemma': 'llarg', 'wronglemma': 'llargu'}
63_52 {'id': '63_52', 'sentence_id': '63', 'tok_id': '52', 'lemma error': True, 'form1': 'llargues', 'form2': 'llargues', 'rightlemma': 'llarg', 'wronglemma': 'llargu'}
64_32 {'id': '64_32', 'sentence_id': '64', 'tok_id': '32', 'lemma error': True, 'form1': 'una', 'form2': 'una', 'rightlemma': 'un', 'wronglemma': 'una'}
64_42 {'id': '64_42', 'sentence_id': '64', 'tok_id': '42', 'lemma error': True, 'form1': 'Guardes', 'form2': 'guardes', 'rightlemma': 'Guardes', 'wronglemma': 'guarda'}
64_43 {'id': '64_43', 'sentence_id': '64', 'tok_id': '43', 'lemma error': True, 'form1': 'Forestals', 'form2': 'forestals', 'rightlemma': 'Forestals', 'wronglemma': 'forestal'}
64_63 {'id': '64_63', 'sentence_id': '64', 'tok_id': '63', 'lemma error': True, 'form1': 'una', 'form2': 'una', 'rightlemma': 'un', 'wronglemma': 'una'}
66_18 {'id': '66_18', 'sentence_id': '66', 'tok_id': '18', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
66_24 {'id': '66_24', 'sentence_id': '66', 'tok_id': '24', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
67_3 {'id': '67_3', 'sentence_id': '67', 'tok_id': '3', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
68_5 {'id': '68_5', 'sentence_id': '68', 'tok_id': '5', 'lemma error': True, 'form1': 'reconeixia', 'form2': 'reconeixia', 'rightlemma': 'reconèixer', 'wronglemma': 'reconeixiar'}
69_10 {'id': '69_10', 'sentence_id': '69', 'tok_id': '10', 'lemma error': True, 'form1': 'participin', 'form2': 'participin', 'rightlemma': 'participar', 'wronglemma': 'participir'}
70_20 {'id': '70_20', 'sentence_id': '70', 'tok_id': '20', 'lemma error': True, 'form1': 'vulguin', 'form2': 'vulguin', 'rightlemma': 'voler', 'wronglemma': 'vulguir'}
72_8 {'id': '72_8', 'sentence_id': '72', 'tok_id': '8', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
72_23 {'id': '72_23', 'sentence_id': '72', 'tok_id': '23', 'lemma error': True, 'form1': 'la', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
75_26 {'id': '75_26', 'sentence_id': '75', 'tok_id': '26', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
75_41 {'id': '75_41', 'sentence_id': '75', 'tok_id': '41', 'lemma error': True, 'form1': 'la', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
77_43 {'id': '77_43', 'sentence_id': '77', 'tok_id': '43', 'lemma error': True, 'form1': 'Terres', 'form2': 'terres', 'rightlemma': 'Terres', 'wronglemma': 'terra'}
78_9 {'id': '78_9', 'sentence_id': '78', 'tok_id': '9', 'lemma error': True, 'form1': 'la', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
79_12 {'id': '79_12', 'sentence_id': '79', 'tok_id': '12', 'lemma error': True, 'form1': 'conegui', 'form2': 'conegui', 'rightlemma': 'conèixer', 'wronglemma': 'coneguar'}
81_23 {'id': '81_23', 'sentence_id': '81', 'tok_id': '23', 'lemma error': True, 'form1': 'vindrà', 'form2': 'vindrà', 'rightlemma': 'venir', 'wronglemma': 'vindrar'}
83_38 {'id': '83_38', 'sentence_id': '83', 'tok_id': '38', 'lemma error': True, 'form1': 'Recursos', 'form2': 'recursos', 'rightlemma': 'Recursos', 'wronglemma': 'recurs'}
85_15 {'id': '85_15', 'sentence_id': '85', 'tok_id': '15', 'lemma error': True, 'form1': 'li', 'form2': 'li', 'rightlemma': 'ell', 'wronglemma': 'li'}
86_37 {'id': '86_37', 'sentence_id': '86', 'tok_id': '37', 'lemma error': True, 'form1': 'Idiomes', 'form2': 'idiomes', 'rightlemma': 'Idiomes', 'wronglemma': 'idioma'}
87_12 {'id': '87_12', 'sentence_id': '87', 'tok_id': '12', 'lemma error': True, 'form1': 'la', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
88_25 {'id': '88_25', 'sentence_id': '88', 'tok_id': '25', 'lemma error': True, 'form1': 'Cures', 'form2': 'cures', 'rightlemma': 'Cures', 'wronglemma': 'cura'}
88_26 {'id': '88_26', 'sentence_id': '88', 'tok_id': '26', 'lemma error': True, 'form1': 'Intensives', 'form2': 'intensives', 'rightlemma': 'Intensives', 'wronglemma': 'intensiu'}
89_17 {'id': '89_17', 'sentence_id': '89', 'tok_id': '17', 'lemma error': True, 'form1': 'La', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
89_34 {'id': '89_34', 'sentence_id': '89', 'tok_id': '34', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
91_7 {'id': '91_7', 'sentence_id': '91', 'tok_id': '7', 'lemma error': True, 'form1': 'romanen', 'form2': 'romanen', 'rightlemma': 'romandre', 'wronglemma': 'romanar'}
92_12 {'id': '92_12', 'sentence_id': '92', 'tok_id': '12', 'lemma error': True, 'form1': 'Alta', 'form2': 'alta', 'rightlemma': 'Alta', 'wronglemma': 'alt'}
97_11 {'id': '97_11', 'sentence_id': '97', 'tok_id': '11', 'lemma error': True, 'form1': 'quina', 'form2': 'quina', 'rightlemma': 'quin', 'wronglemma': 'quina'}
98_19 {'id': '98_19', 'sentence_id': '98', 'tok_id': '19', 'lemma error': True, 'form1': 'Metropolitana', 'form2': 'metropolitana', 'rightlemma': 'Metropolitana', 'wronglemma': 'metropolità'}
98_22 {'id': '98_22', 'sentence_id': '98', 'tok_id': '22', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
99_8 {'id': '99_8', 'sentence_id': '99', 'tok_id': '8', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
100_18 {'id': '100_18', 'sentence_id': '100', 'tok_id': '18', 'lemma error': True, 'form1': 'Alta', 'form2': 'alta', 'rightlemma': 'Alta', 'wronglemma': 'alt'}
100_49 {'id': '100_49', 'sentence_id': '100', 'tok_id': '49', 'lemma error': True, 'form1': 'seria', 'form2': 'seria', 'rightlemma': 'seriar', 'wronglemma': 'ser'}
100_63 {'id': '100_63', 'sentence_id': '100', 'tok_id': '63', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
101_15 {'id': '101_15', 'sentence_id': '101', 'tok_id': '15', 'lemma error': True, 'form1': 'Metropolitana', 'form2': 'metropolitana', 'rightlemma': 'Metropolitana', 'wronglemma': 'metropolità'}
103_2 {'id': '103_2', 'sentence_id': '103', 'tok_id': '2', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
103_18 {'id': '103_18', 'sentence_id': '103', 'tok_id': '18', 'lemma error': True, 'form1': 'accessos', 'form2': 'accessos', 'rightlemma': 'accés', 'wronglemma': 'accesso'}
105_3 {'id': '105_3', 'sentence_id': '105', 'tok_id': '3', 'lemma error': True, 'form1': 'accessos', 'form2': 'accessos', 'rightlemma': 'accés', 'wronglemma': 'accesso'}
105_18 {'id': '105_18', 'sentence_id': '105', 'tok_id': '18', 'lemma error': True, 'form1': 'gràcies', 'form2': 'gràcies', 'rightlemma': 'gràcies', 'wronglemma': 'gràcia'}
105_30 {'id': '105_30', 'sentence_id': '105', 'tok_id': '30', 'lemma error': True, 'form1': 'Ferrocarrils', 'form2': 'ferrocarrils', 'rightlemma': 'Ferrocarrils', 'wronglemma': 'ferrocarril'}
105_32 {'id': '105_32', 'sentence_id': '105', 'tok_id': '32', 'lemma error': True, 'form1': 'la', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
105_39 {'id': '105_39', 'sentence_id': '105', 'tok_id': '39', 'lemma error': True, 'form1': 'Rodalies', 'form2': 'rodalies', 'rightlemma': 'Rodalies', 'wronglemma': 'rodalia'}
106_4 {'id': '106_4', 'sentence_id': '106', 'tok_id': '4', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
106_10 {'id': '106_10', 'sentence_id': '106', 'tok_id': '10', 'lemma error': True, 'form1': 'accessos', 'form2': 'accessos', 'rightlemma': 'accés', 'wronglemma': 'accesso'}
108_8 {'id': '108_8', 'sentence_id': '108', 'tok_id': '8', 'lemma error': True, 'form1': 'Públiques', 'form2': 'públiques', 'rightlemma': 'Públiques', 'wronglemma': 'públic'}
108_29 {'id': '108_29', 'sentence_id': '108', 'tok_id': '29', 'lemma error': True, 'form1': 'Ferrocarrils', 'form2': 'ferrocarrils', 'rightlemma': 'Ferrocarrils', 'wronglemma': 'ferrocarril'}
108_31 {'id': '108_31', 'sentence_id': '108', 'tok_id': '31', 'lemma error': True, 'form1': 'la', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
109_9 {'id': '109_9', 'sentence_id': '109', 'tok_id': '9', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
109_15 {'id': '109_15', 'sentence_id': '109', 'tok_id': '15', 'lemma error': True, 'form1': 'malmeses', 'form2': 'malmeses', 'rightlemma': 'malmès', 'wronglemma': 'malmes'}
114_10 {'id': '114_10', 'sentence_id': '114', 'tok_id': '10', 'lemma error': True, 'form1': 'Ferrocarrils', 'form2': 'ferrocarrils', 'rightlemma': 'Ferrocarrils', 'wronglemma': 'ferrocarril'}
114_12 {'id': '114_12', 'sentence_id': '114', 'tok_id': '12', 'lemma error': True, 'form1': 'la', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
114_62 {'id': '114_62', 'sentence_id': '114', 'tok_id': '62', 'lemma error': True, 'form1': 'pugen', 'form2': 'pugen', 'rightlemma': 'pujar', 'wronglemma': 'pugar'}
117_27 {'id': '117_27', 'sentence_id': '117', 'tok_id': '27', 'lemma error': True, 'form1': 'pelegrins', 'form2': 'pelegrins', 'rightlemma': 'pelegrí', 'wronglemma': 'pelegrin'}
122_3 {'id': '122_3', 'sentence_id': '122', 'tok_id': '3', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
122_13 {'id': '122_13', 'sentence_id': '122', 'tok_id': '13', 'lemma error': True, 'form1': 'pelegrins', 'form2': 'pelegrins', 'rightlemma': 'pelegrí', 'wronglemma': 'pelegrin'}
124_4 {'id': '124_4', 'sentence_id': '124', 'tok_id': '4', 'lemma error': True, 'form1': 'la', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
124_8 {'id': '124_8', 'sentence_id': '124', 'tok_id': '8', 'lemma error': True, 'form1': 'estat', 'form2': 'estat', 'rightlemma': 'estar', 'wronglemma': 'ser'}
126_14 {'id': '126_14', 'sentence_id': '126', 'tok_id': '14', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
126_15 {'id': '126_15', 'sentence_id': '126', 'tok_id': '15', 'lemma error': True, 'form1': 'veia', 'form2': 'veia', 'rightlemma': 'veure', 'wronglemma': 'veiar'}
127_5 {'id': '127_5', 'sentence_id': '127', 'tok_id': '5', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
128_11 {'id': '128_11', 'sentence_id': '128', 'tok_id': '11', 'lemma error': True, 'form1': 'Ferrocarrils', 'form2': 'ferrocarrils', 'rightlemma': 'Ferrocarrils', 'wronglemma': 'ferrocarril'}
128_13 {'id': '128_13', 'sentence_id': '128', 'tok_id': '13', 'lemma error': True, 'form1': 'la', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
128_34 {'id': '128_34', 'sentence_id': '128', 'tok_id': '34', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
130_17 {'id': '130_17', 'sentence_id': '130', 'tok_id': '17', 'lemma error': True, 'form1': 'Normes', 'form2': 'normes', 'rightlemma': 'Normes', 'wronglemma': 'norma'}
130_18 {'id': '130_18', 'sentence_id': '130', 'tok_id': '18', 'lemma error': True, 'form1': 'Subsidiàries', 'form2': 'subsidiàries', 'rightlemma': 'Subsidiàries', 'wronglemma': 'subsidiari'}
130_20 {'id': '130_20', 'sentence_id': '130', 'tok_id': '20', 'lemma error': True, 'form1': 'Complementàries', 'form2': 'complementàries', 'rightlemma': 'Complementàries', 'wronglemma': 'complementari'}
130_27 {'id': '130_27', 'sentence_id': '130', 'tok_id': '27', 'lemma error': True, 'form1': 'directa', 'form2': 'directa', 'rightlemma': 'directe', 'wronglemma': 'direct'}
130_55 {'id': '130_55', 'sentence_id': '130', 'tok_id': '55', 'lemma error': True, 'form1': 'Normes', 'form2': 'normes', 'rightlemma': 'Normes', 'wronglemma': 'norma'}
130_56 {'id': '130_56', 'sentence_id': '130', 'tok_id': '56', 'lemma error': True, 'form1': 'Subsidiàries', 'form2': 'subsidiàries', 'rightlemma': 'Subsidiàries', 'wronglemma': 'subsidiari'}
132_35 {'id': '132_35', 'sentence_id': '132', 'tok_id': '35', 'lemma error': True, 'form1': 'Piles', 'form2': 'piles', 'rightlemma': 'Piles', 'wronglemma': 'pila'}
132_60 {'id': '132_60', 'sentence_id': '132', 'tok_id': '60', 'lemma error': True, 'form1': 'La', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
132_69 {'id': '132_69', 'sentence_id': '132', 'tok_id': '69', 'lemma error': True, 'form1': 'La', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
132_87 {'id': '132_87', 'sentence_id': '132', 'tok_id': '87', 'lemma error': True, 'form1': 'La', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}

In [16]:
for keys, values in d_err.items():
    print(keys, "*", values)

1_48 * {'id': '1_48', 'sentence_id': '1', 'tok_id': '48', 'lemma error': True, 'form1': 'càrniques', 'form2': 'càrniques', 'rightlemma': 'càrnic', 'wronglemma': 'càrniqu'}
3_14 * {'id': '3_14', 'sentence_id': '3', 'tok_id': '14', 'lemma error': True, 'form1': 'càrniques', 'form2': 'càrniques', 'rightlemma': 'càrnic', 'wronglemma': 'càrniqu'}
3_16 * {'id': '3_16', 'sentence_id': '3', 'tok_id': '16', 'lemma error': True, 'form1': 'La', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
4_12 * {'id': '4_12', 'sentence_id': '4', 'tok_id': '12', 'lemma error': True, 'form1': 'una', 'form2': 'una', 'rightlemma': 'un', 'wronglemma': 'una'}
7_15 * {'id': '7_15', 'sentence_id': '7', 'tok_id': '15', 'lemma error': True, 'form1': 'desconeguessin', 'form2': 'desconeguessin', 'rightlemma': 'desconèixer', 'wronglemma': 'desconeguar'}
8_6 * {'id': '8_6', 'sentence_id': '8', 'tok_id': '6', 'lemma error': True, 'form1': 'Fomento', 'form2': 'fomento', 'rightlemma': 'Fomento', 'wronglemma': 'fomentar'}
12_15 * {'id': '12_15', 'sentence_id': '12', 'tok_id': '15', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
15_11 * {'id': '15_11', 'sentence_id': '15', 'tok_id': '11', 'lemma error': True, 'form1': 'Relacions', 'form2': 'relacions', 'rightlemma': 'Relacions', 'wronglemma': 'relació', 'deprel error': True, 'rightdeprel': 'nmod', 'wrongdeprel': 'flat'}
15_12 * {'id': '15_12', 'sentence_id': '15', 'tok_id': '12', 'lemma error': True, 'form1': 'Laborals', 'form2': 'laborals', 'rightlemma': 'Laborals', 'wronglemma': 'laboral', 'head error': True, 'righthead': '11', 'wronghead': '8'}
15_27 * {'id': '15_27', 'sentence_id': '15', 'tok_id': '27', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
16_19 * {'id': '16_19', 'sentence_id': '16', 'tok_id': '19', 'lemma error': True, 'form1': 'la', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
16_34 * {'id': '16_34', 'sentence_id': '16', 'tok_id': '34', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
18_8 * {'id': '18_8', 'sentence_id': '18', 'tok_id': '8', 'lemma error': True, 'form1': 'una', 'form2': 'una', 'rightlemma': 'un', 'wronglemma': 'una'}
19_5 * {'id': '19_5', 'sentence_id': '19', 'tok_id': '5', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
19_17 * {'id': '19_17', 'sentence_id': '19', 'tok_id': '17', 'lemma error': True, 'form1': 'acumulin', 'form2': 'acumulin', 'rightlemma': 'acumular', 'wronglemma': 'acumulir'}
20_3 * {'id': '20_3', 'sentence_id': '20', 'tok_id': '3', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
21_37 * {'id': '21_37', 'sentence_id': '21', 'tok_id': '37', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
27_13 * {'id': '27_13', 'sentence_id': '27', 'tok_id': '13', 'lemma error': True, 'form1': 'Tributària', 'form2': 'tributària', 'rightlemma': 'Tributària', 'wronglemma': 'tributari'}
32_18 * {'id': '32_18', 'sentence_id': '32', 'tok_id': '18', 'lemma error': True, 'form1': 'una', 'form2': 'una', 'rightlemma': 'un', 'wronglemma': 'una'}
32_30 * {'id': '32_30', 'sentence_id': '32', 'tok_id': '30', 'lemma error': True, 'form1': 'és', 'form2': 'és', 'rightlemma': 'és', 'wronglemma': 'ser', 'upos error': True, 'rightupos': 'NOUN', 'wrongupos': 'AUX'}
34_12 * {'id': '34_12', 'sentence_id': '34', 'tok_id': '12', 'lemma error': True, 'form1': 'ho', 'form2': 'ho', 'rightlemma': 'ell', 'wronglemma': 'ho'}
34_20 * {'id': '34_20', 'sentence_id': '34', 'tok_id': '20', 'lemma error': True, 'form1': 'ens', 'form2': 'ens', 'rightlemma': 'jo', 'wronglemma': 'nos'}
37_15 * {'id': '37_15', 'sentence_id': '37', 'tok_id': '15', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
37_29 * {'id': '37_29', 'sentence_id': '37', 'tok_id': '29', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
37_30 * {'id': '37_30', 'sentence_id': '37', 'tok_id': '30', 'lemma error': True, 'form1': 'preveuen', 'form2': 'preveuen', 'rightlemma': 'preveure', 'wronglemma': 'preveuar'}
38_23 * {'id': '38_23', 'sentence_id': '38', 'tok_id': '23', 'lemma error': True, 'form1': 'propietària', 'form2': 'propietària', 'rightlemma': 'propietari', 'wronglemma': 'propietàri'}
43_55 * {'id': '43_55', 'sentence_id': '43', 'tok_id': '55', 'lemma error': True, 'form1': 'amenacin', 'form2': 'amenacin', 'rightlemma': 'amenaçar', 'wronglemma': 'amenacir'}
44_24 * {'id': '44_24', 'sentence_id': '44', 'tok_id': '24', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
49_33 * {'id': '49_33', 'sentence_id': '49', 'tok_id': '33', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
50_31 * {'id': '50_31', 'sentence_id': '50', 'tok_id': '31', 'lemma error': True, 'form1': 'congressos', 'form2': 'congressos', 'rightlemma': 'congrés', 'wronglemma': 'congresso'}
51_16 * {'id': '51_16', 'sentence_id': '51', 'tok_id': '16', 'lemma error': True, 'form1': 'rebi', 'form2': 'rebi', 'rightlemma': 'rebre', 'wronglemma': 'rebar'}
52_37 * {'id': '52_37', 'sentence_id': '52', 'tok_id': '37', 'lemma error': True, 'form1': 'congressos', 'form2': 'congressos', 'rightlemma': 'congrés', 'wronglemma': 'congresso'}
53_4 * {'id': '53_4', 'sentence_id': '53', 'tok_id': '4', 'lemma error': True, 'form1': 'provenen', 'form2': 'provenen', 'rightlemma': 'provenir', 'wronglemma': 'provenar'}
53_13 * {'id': '53_13', 'sentence_id': '53', 'tok_id': '13', 'lemma error': True, 'form1': 'una', 'form2': 'una', 'rightlemma': 'un', 'wronglemma': 'una'}
53_28 * {'id': '53_28', 'sentence_id': '53', 'tok_id': '28', 'lemma error': True, 'form1': 'Escaldes', 'form2': 'escaldes', 'rightlemma': 'Escaldes', 'wronglemma': 'escaldar'}
54_23 * {'id': '54_23', 'sentence_id': '54', 'tok_id': '23', 'lemma error': True, 'form1': 'Socioculturals', 'form2': 'socioculturals', 'rightlemma': 'Socioculturals', 'wronglemma': 'sociocultural'}
55_3 * {'id': '55_3', 'sentence_id': '55', 'tok_id': '3', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
55_14 * {'id': '55_14', 'sentence_id': '55', 'tok_id': '14', 'lemma error': True, 'form1': 'pretenen', 'form2': 'pretenen', 'rightlemma': 'pretendre', 'wronglemma': 'pretenar'}
56_15 * {'id': '56_15', 'sentence_id': '56', 'tok_id': '15', 'lemma error': True, 'form1': 'rebi', 'form2': 'rebi', 'rightlemma': 'rebre', 'wronglemma': 'rebar'}
60_4 * {'id': '60_4', 'sentence_id': '60', 'tok_id': '4', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
60_26 * {'id': '60_26', 'sentence_id': '60', 'tok_id': '26', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
60_27 * {'id': '60_27', 'sentence_id': '60', 'tok_id': '27', 'lemma error': True, 'form1': 'busquin', 'form2': 'busquin', 'rightlemma': 'buscar', 'wronglemma': 'busquir'}
62_10 * {'id': '62_10', 'sentence_id': '62', 'tok_id': '10', 'lemma error': True, 'form1': 'processos', 'form2': 'processos', 'rightlemma': 'procés', 'wronglemma': 'processo'}
63_16 * {'id': '63_16', 'sentence_id': '63', 'tok_id': '16', 'lemma error': True, 'form1': 'processos', 'form2': 'processos', 'rightlemma': 'procés', 'wronglemma': 'processo', 'deprel error': True, 'rightdeprel': 'obl:arg', 'wrongdeprel': 'obj'}
63_40 * {'id': '63_40', 'sentence_id': '63', 'tok_id': '40', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
63_41 * {'id': '63_41', 'sentence_id': '63', 'tok_id': '41', 'lemma error': True, 'form1': 'queixin', 'form2': 'queixin', 'rightlemma': 'queixar-se', 'wronglemma': 'queixir'}
63_44 * {'id': '63_44', 'sentence_id': '63', 'tok_id': '44', 'lemma error': True, 'form1': 'llargues', 'form2': 'llargues', 'rightlemma': 'llarg', 'wronglemma': 'llargu'}
63_52 * {'id': '63_52', 'sentence_id': '63', 'tok_id': '52', 'lemma error': True, 'form1': 'llargues', 'form2': 'llargues', 'rightlemma': 'llarg', 'wronglemma': 'llargu'}
64_32 * {'id': '64_32', 'sentence_id': '64', 'tok_id': '32', 'lemma error': True, 'form1': 'una', 'form2': 'una', 'rightlemma': 'un', 'wronglemma': 'una'}
64_42 * {'id': '64_42', 'sentence_id': '64', 'tok_id': '42', 'lemma error': True, 'form1': 'Guardes', 'form2': 'guardes', 'rightlemma': 'Guardes', 'wronglemma': 'guarda', 'upos error': True, 'rightupos': 'PROPN', 'wrongupos': 'NOUN', 'deprel error': True, 'rightdeprel': 'nmod', 'wrongdeprel': 'obj'}
64_43 * {'id': '64_43', 'sentence_id': '64', 'tok_id': '43', 'lemma error': True, 'form1': 'Forestals', 'form2': 'forestals', 'rightlemma': 'Forestals', 'wronglemma': 'forestal', 'upos error': True, 'rightupos': 'PROPN', 'wrongupos': 'ADJ', 'deprel error': True, 'rightdeprel': 'flat', 'wrongdeprel': 'amod'}
64_63 * {'id': '64_63', 'sentence_id': '64', 'tok_id': '63', 'lemma error': True, 'form1': 'una', 'form2': 'una', 'rightlemma': 'un', 'wronglemma': 'una'}
66_18 * {'id': '66_18', 'sentence_id': '66', 'tok_id': '18', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
66_24 * {'id': '66_24', 'sentence_id': '66', 'tok_id': '24', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
67_3 * {'id': '67_3', 'sentence_id': '67', 'tok_id': '3', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
68_5 * {'id': '68_5', 'sentence_id': '68', 'tok_id': '5', 'lemma error': True, 'form1': 'reconeixia', 'form2': 'reconeixia', 'rightlemma': 'reconèixer', 'wronglemma': 'reconeixiar'}
69_10 * {'id': '69_10', 'sentence_id': '69', 'tok_id': '10', 'lemma error': True, 'form1': 'participin', 'form2': 'participin', 'rightlemma': 'participar', 'wronglemma': 'participir'}
70_20 * {'id': '70_20', 'sentence_id': '70', 'tok_id': '20', 'lemma error': True, 'form1': 'vulguin', 'form2': 'vulguin', 'rightlemma': 'voler', 'wronglemma': 'vulguir'}
72_8 * {'id': '72_8', 'sentence_id': '72', 'tok_id': '8', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se', 'deprel error': True, 'rightdeprel': 'obl:arg', 'wrongdeprel': 'iobj'}
72_23 * {'id': '72_23', 'sentence_id': '72', 'tok_id': '23', 'lemma error': True, 'form1': 'la', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
75_26 * {'id': '75_26', 'sentence_id': '75', 'tok_id': '26', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
75_41 * {'id': '75_41', 'sentence_id': '75', 'tok_id': '41', 'lemma error': True, 'form1': 'la', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
77_43 * {'id': '77_43', 'sentence_id': '77', 'tok_id': '43', 'lemma error': True, 'form1': 'Terres', 'form2': 'terres', 'rightlemma': 'Terres', 'wronglemma': 'terra', 'upos error': True, 'rightupos': 'PROPN', 'wrongupos': 'NOUN'}
78_9 * {'id': '78_9', 'sentence_id': '78', 'tok_id': '9', 'lemma error': True, 'form1': 'la', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
79_12 * {'id': '79_12', 'sentence_id': '79', 'tok_id': '12', 'lemma error': True, 'form1': 'conegui', 'form2': 'conegui', 'rightlemma': 'conèixer', 'wronglemma': 'coneguar'}
81_23 * {'id': '81_23', 'sentence_id': '81', 'tok_id': '23', 'lemma error': True, 'form1': 'vindrà', 'form2': 'vindrà', 'rightlemma': 'venir', 'wronglemma': 'vindrar'}
83_38 * {'id': '83_38', 'sentence_id': '83', 'tok_id': '38', 'lemma error': True, 'form1': 'Recursos', 'form2': 'recursos', 'rightlemma': 'Recursos', 'wronglemma': 'recurs'}
85_15 * {'id': '85_15', 'sentence_id': '85', 'tok_id': '15', 'lemma error': True, 'form1': 'li', 'form2': 'li', 'rightlemma': 'ell', 'wronglemma': 'li'}
86_37 * {'id': '86_37', 'sentence_id': '86', 'tok_id': '37', 'lemma error': True, 'form1': 'Idiomes', 'form2': 'idiomes', 'rightlemma': 'Idiomes', 'wronglemma': 'idioma'}
87_12 * {'id': '87_12', 'sentence_id': '87', 'tok_id': '12', 'lemma error': True, 'form1': 'la', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
88_25 * {'id': '88_25', 'sentence_id': '88', 'tok_id': '25', 'lemma error': True, 'form1': 'Cures', 'form2': 'cures', 'rightlemma': 'Cures', 'wronglemma': 'cura', 'upos error': True, 'rightupos': 'PROPN', 'wrongupos': 'NOUN', 'deprel error': True, 'rightdeprel': 'flat', 'wrongdeprel': 'nmod'}
88_26 * {'id': '88_26', 'sentence_id': '88', 'tok_id': '26', 'lemma error': True, 'form1': 'Intensives', 'form2': 'intensives', 'rightlemma': 'Intensives', 'wronglemma': 'intensiu', 'upos error': True, 'rightupos': 'PROPN', 'wrongupos': 'ADJ', 'deprel error': True, 'rightdeprel': 'flat', 'wrongdeprel': 'amod'}
89_17 * {'id': '89_17', 'sentence_id': '89', 'tok_id': '17', 'lemma error': True, 'form1': 'La', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el', 'head error': True, 'righthead': '20', 'wronghead': '18'}
89_34 * {'id': '89_34', 'sentence_id': '89', 'tok_id': '34', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
91_7 * {'id': '91_7', 'sentence_id': '91', 'tok_id': '7', 'lemma error': True, 'form1': 'romanen', 'form2': 'romanen', 'rightlemma': 'romandre', 'wronglemma': 'romanar'}
92_12 * {'id': '92_12', 'sentence_id': '92', 'tok_id': '12', 'lemma error': True, 'form1': 'Alta', 'form2': 'alta', 'rightlemma': 'Alta', 'wronglemma': 'alt', 'upos error': True, 'rightupos': 'PROPN', 'wrongupos': 'ADJ', 'head error': True, 'righthead': '10', 'wronghead': '13', 'deprel error': True, 'rightdeprel': 'flat', 'wrongdeprel': 'amod'}
97_11 * {'id': '97_11', 'sentence_id': '97', 'tok_id': '11', 'lemma error': True, 'form1': 'quina', 'form2': 'quina', 'rightlemma': 'quin', 'wronglemma': 'quina', 'head error': True, 'righthead': '10', 'wronghead': '8', 'deprel error': True, 'rightdeprel': 'xcomp', 'wrongdeprel': 'acl'}
98_19 * {'id': '98_19', 'sentence_id': '98', 'tok_id': '19', 'lemma error': True, 'form1': 'Metropolitana', 'form2': 'metropolitana', 'rightlemma': 'Metropolitana', 'wronglemma': 'metropolità'}
98_22 * {'id': '98_22', 'sentence_id': '98', 'tok_id': '22', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
99_8 * {'id': '99_8', 'sentence_id': '99', 'tok_id': '8', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
100_18 * {'id': '100_18', 'sentence_id': '100', 'tok_id': '18', 'lemma error': True, 'form1': 'Alta', 'form2': 'alta', 'rightlemma': 'Alta', 'wronglemma': 'alt', 'upos error': True, 'rightupos': 'PROPN', 'wrongupos': 'ADJ', 'head error': True, 'righthead': '16', 'wronghead': '19', 'deprel error': True, 'rightdeprel': 'flat', 'wrongdeprel': 'amod'}
100_49 * {'id': '100_49', 'sentence_id': '100', 'tok_id': '49', 'lemma error': True, 'form1': 'seria', 'form2': 'seria', 'rightlemma': 'seriar', 'wronglemma': 'ser'}
100_63 * {'id': '100_63', 'sentence_id': '100', 'tok_id': '63', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
101_15 * {'id': '101_15', 'sentence_id': '101', 'tok_id': '15', 'lemma error': True, 'form1': 'Metropolitana', 'form2': 'metropolitana', 'rightlemma': 'Metropolitana', 'wronglemma': 'metropolità'}
103_2 * {'id': '103_2', 'sentence_id': '103', 'tok_id': '2', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
103_18 * {'id': '103_18', 'sentence_id': '103', 'tok_id': '18', 'lemma error': True, 'form1': 'accessos', 'form2': 'accessos', 'rightlemma': 'accés', 'wronglemma': 'accesso'}
105_3 * {'id': '105_3', 'sentence_id': '105', 'tok_id': '3', 'lemma error': True, 'form1': 'accessos', 'form2': 'accessos', 'rightlemma': 'accés', 'wronglemma': 'accesso'}
105_18 * {'id': '105_18', 'sentence_id': '105', 'tok_id': '18', 'lemma error': True, 'form1': 'gràcies', 'form2': 'gràcies', 'rightlemma': 'gràcies', 'wronglemma': 'gràcia'}
105_30 * {'id': '105_30', 'sentence_id': '105', 'tok_id': '30', 'lemma error': True, 'form1': 'Ferrocarrils', 'form2': 'ferrocarrils', 'rightlemma': 'Ferrocarrils', 'wronglemma': 'ferrocarril'}
105_32 * {'id': '105_32', 'sentence_id': '105', 'tok_id': '32', 'lemma error': True, 'form1': 'la', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
105_39 * {'id': '105_39', 'sentence_id': '105', 'tok_id': '39', 'lemma error': True, 'form1': 'Rodalies', 'form2': 'rodalies', 'rightlemma': 'Rodalies', 'wronglemma': 'rodalia'}
106_4 * {'id': '106_4', 'sentence_id': '106', 'tok_id': '4', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
106_10 * {'id': '106_10', 'sentence_id': '106', 'tok_id': '10', 'lemma error': True, 'form1': 'accessos', 'form2': 'accessos', 'rightlemma': 'accés', 'wronglemma': 'accesso'}
108_8 * {'id': '108_8', 'sentence_id': '108', 'tok_id': '8', 'lemma error': True, 'form1': 'Públiques', 'form2': 'públiques', 'rightlemma': 'Públiques', 'wronglemma': 'públic'}
108_29 * {'id': '108_29', 'sentence_id': '108', 'tok_id': '29', 'lemma error': True, 'form1': 'Ferrocarrils', 'form2': 'ferrocarrils', 'rightlemma': 'Ferrocarrils', 'wronglemma': 'ferrocarril'}
108_31 * {'id': '108_31', 'sentence_id': '108', 'tok_id': '31', 'lemma error': True, 'form1': 'la', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
109_9 * {'id': '109_9', 'sentence_id': '109', 'tok_id': '9', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
109_15 * {'id': '109_15', 'sentence_id': '109', 'tok_id': '15', 'lemma error': True, 'form1': 'malmeses', 'form2': 'malmeses', 'rightlemma': 'malmès', 'wronglemma': 'malmes'}
114_10 * {'id': '114_10', 'sentence_id': '114', 'tok_id': '10', 'lemma error': True, 'form1': 'Ferrocarrils', 'form2': 'ferrocarrils', 'rightlemma': 'Ferrocarrils', 'wronglemma': 'ferrocarril'}
114_12 * {'id': '114_12', 'sentence_id': '114', 'tok_id': '12', 'lemma error': True, 'form1': 'la', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
114_62 * {'id': '114_62', 'sentence_id': '114', 'tok_id': '62', 'lemma error': True, 'form1': 'pugen', 'form2': 'pugen', 'rightlemma': 'pujar', 'wronglemma': 'pugar'}
117_27 * {'id': '117_27', 'sentence_id': '117', 'tok_id': '27', 'lemma error': True, 'form1': 'pelegrins', 'form2': 'pelegrins', 'rightlemma': 'pelegrí', 'wronglemma': 'pelegrin'}
122_3 * {'id': '122_3', 'sentence_id': '122', 'tok_id': '3', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
122_13 * {'id': '122_13', 'sentence_id': '122', 'tok_id': '13', 'lemma error': True, 'form1': 'pelegrins', 'form2': 'pelegrins', 'rightlemma': 'pelegrí', 'wronglemma': 'pelegrin'}
124_4 * {'id': '124_4', 'sentence_id': '124', 'tok_id': '4', 'lemma error': True, 'form1': 'la', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
124_8 * {'id': '124_8', 'sentence_id': '124', 'tok_id': '8', 'lemma error': True, 'form1': 'estat', 'form2': 'estat', 'rightlemma': 'estar', 'wronglemma': 'ser'}
126_14 * {'id': '126_14', 'sentence_id': '126', 'tok_id': '14', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
126_15 * {'id': '126_15', 'sentence_id': '126', 'tok_id': '15', 'lemma error': True, 'form1': 'veia', 'form2': 'veia', 'rightlemma': 'veure', 'wronglemma': 'veiar'}
127_5 * {'id': '127_5', 'sentence_id': '127', 'tok_id': '5', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}
128_11 * {'id': '128_11', 'sentence_id': '128', 'tok_id': '11', 'lemma error': True, 'form1': 'Ferrocarrils', 'form2': 'ferrocarrils', 'rightlemma': 'Ferrocarrils', 'wronglemma': 'ferrocarril'}
128_13 * {'id': '128_13', 'sentence_id': '128', 'tok_id': '13', 'lemma error': True, 'form1': 'la', 'form2': 'la', 'rightlemma': 'la', 'wronglemma': 'el'}
128_34 * {'id': '128_34', 'sentence_id': '128', 'tok_id': '34', 'lemma error': True, 'form1': 'es', 'form2': 'es', 'rightlemma': 'ell', 'wronglemma': 'se'}

In [14]:
import pandas as pd
from spacy_pickle import pickle_read

err_low = pickle_read("200_ca_spacy_low.pickle")
err_nolow= pickle_read("200_ca_spacy.pickle")
err_dif= pickle_read("200_ca_spacy_low_vs_nolow.pickle")

df_low= pd.DataFrame.from_dict(err_low, orient="index")
df_nolow= pd.DataFrame.from_dict(err_nolow, orient="index")
df_dif= pd.DataFrame.from_dict(err_dif, orient="index")

In [15]:
df_low.describe()

,id,sentence_id,tok_id,lemma error,form1,form2,rightlemma,wronglemma,upos error,rightupos,wrongupos,head error,righthead,wronghead
count,248,248,248,138,248,248,138,138,35,35,35,75,75,75
unique,248,117,59,1,132,132,50,52,1,3,6,1,38,36
top,1_48,114,15,True,es,es,ell,se,True,NOUN,PROPN,True,10,11
freq,1,8,11,138,41,41,46,42,35,23,29,75,9,6

In [16]:
df_nolow.describe()

,id,sentence_id,tok_id,lemma error,form1,form2,rightlemma,wronglemma,upos error,rightupos,wrongupos,head error,righthead,wronghead
count,248,248,248,149,248,248,149,149,6,6,6,93,93,93
unique,248,109,82,1,135,135,50,52,1,3,4,1,39,38
top,1_48,132,10,True,es,es,ell,se,True,NOUN,DET,True,60,4
freq,1,31,11,149,41,41,47,43,6,2,2,93,14,20

In [17]:
df_dif.describe()

,id,sentence_id,tok_id,upos error,form1,form2,rightupos,wrongupos,head error,righthead,wronghead
count,55,55,55,31,55,55,31,31,24,24,24
unique,55,38,30,1,43,43,3,4,1,19,19
top,159_20,15,10,True,comarcal,comarcal,PROPN,NOUN,True,9,26
freq,1,3,5,31,3,3,29,21,24,3,2

In [36]:
df_nolow[["rightupos", "wrongupos"]]
df_nolow[df_nolow["head error"] == True].describe()

,id,sentence_id,tok_id,lemma error,form1,form2,rightlemma,wronglemma,upos error,rightupos,wrongupos,head error,righthead,wronghead
count,93,93,93,0,93,93,0,0,0,0,0,93,93,93
unique,93,31,60,0,75,75,0,0,0,0,0,1,39,38
top,97_11,132,19,NaN,el,el,NaN,NaN,NaN,NaN,NaN,True,60,4
freq,1,25,5,NaN,7,7,NaN,NaN,NaN,NaN,NaN,93,14,20

In [39]:
df_low[df_low["right "] == True].describe()

,id,sentence_id,tok_id,lemma error,form1,form2,rightlemma,wronglemma,upos error,rightupos,wrongupos,head error,righthead,wronghead
count,138,138,138,138,138,138,138,138,0,0,0,0,0,0
unique,138,95,46,1,54,54,50,52,0,0,0,0,0,0
top,1_48,63,15,True,es,es,ell,se,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,5,9,138,41,41,46,42,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
from read_conllu import test_annotation
import pandas as pd
test_an= test_annotation("ca_ancora-ud-train.conllu","200_ca_spacy_low.conllu",  200, "upos", printf= False)
df_test= pd.DataFrame.from_dict(test_an, orient="index")
print(df_test)

            id sentence_id tok_id  upos error          form1          form2  \
15_8      15_8          15      8        True       direcció       direcció
15_9      15_9          15      9        True        general        general
15_15    15_15          15     15        True    departament    departament
32_30    32_30          32     30        True             és             és
35_19    35_19          35     19        True   conscienciar   conscienciar
35_27    35_27          35     27        True            dir            dir
52_4      52_4          52      4        True         comerç         comerç
56_5      56_5          56      5        True         cambra         cambra
56_7      56_7          56      7        True         comerç         comerç
60_14    60_14          60     14        True        oficina        oficina
60_15    60_15          60     15        True       comarcal       comarcal
61_5      61_5          61      5        True        oficina        oficina
61_6      61_6          61      6        True       comarcal       comarcal
73_27    73_27          73     27        True          tirar          tirar
87_51    87_51          87     51        True        idiomes        idiomes
92_19    92_19          92     19        True          regió          regió
92_20    92_20          92     20        True  metropolitana  metropolitana
97_10    97_10          97     10        True       conèixer       conèixer
111_7    111_7         111      7        True      funicular      funicular
113_40  113_40         113     40        True     funiculars     funiculars
122_24  122_24         122     24        True     monumental     monumental
137_41  137_41         137     41        True             un             un
143_24  143_24         143     24        True        torrent        torrent
144_11  144_11         144     11        True         abonar         abonar
159_20  159_20         159     20        True          parcs          parcs
169_7    169_7         169      7        True         jutjat         jutjat
169_8    169_8         169      8        True         social         social
171_32  171_32         171     32        True         jutjat         jutjat
171_34  171_34         171     34        True     instrucció     instrucció
173_8    173_8         173      8        True         jutjat         jutjat
173_10  173_10         173     10        True     instrucció     instrucció
175_4    175_4         175      4        True            cap            cap
176_36  176_36         176     36        True       consorci       consorci
177_18  177_18         177     18        True        central        central
180_10  180_10         180     10        True       executiu       executiu
182_41  182_41         182     41        True        oficina        oficina
182_42  182_42         182     42        True       comarcal       comarcal
185_9    185_9         185      9        True  administració  administració
187_4    187_4         187      4        True         passar         passar
190_19  190_19         190     19        True    departament    departament
191_8    191_8         191      8        True            una            una
196_6    196_6         196      6        True       establir       establir
197_28  197_28         197     28        True          veïns          veïns

       rightupos wrongupos
15_8        NOUN     PROPN
15_9         ADJ     PROPN
15_15       NOUN     PROPN
32_30       NOUN       AUX
35_19       VERB       AUX
35_27       NOUN      VERB
52_4        NOUN     PROPN
56_5        NOUN     PROPN
56_7        NOUN     PROPN
60_14       NOUN     PROPN
60_15        ADJ     PROPN
61_5        NOUN     PROPN
61_6         ADJ     PROPN
73_27       VERB       AUX
87_51       NOUN     PROPN
92_19       NOUN     PROPN
92_20        ADJ     PROPN
97_10       VERB       AUX
111_7        ADJ      NOUN
113_40       ADJ      NOUN
122_24       ADJ     PROPN
137_41       NUM      PRON
143_24      NOUN     PROPN
144_11      VERB       AUX
159_20      NOUN     PROPN
169_7       NOUN     PROPN
169_8        ADJ     PROPN
171_32      NOUN     PROPN
171_34      NOUN     PROPN
173_8       NOUN     PROPN
173_10      NOUN     PROPN
175_4       NOUN     PROPN
176_36      NOUN     PROPN
177_18       ADJ     PROPN
180_10      NOUN     PROPN
182_41      NOUN     PROPN
182_42       ADJ     PROPN
185_9       NOUN     PROPN
187_4       VERB       AUX
190_19      NOUN     PROPN
191_8        NUM       DET
196_6       VERB       AUX
197_28      NOUN     PROPN

In [3]:
from read_conllu import test_annotation
test_an= test_annotation("ca_ancora-ud-train.conllu","200_ca_spacy_low.conllu",  200, "head", printf= False)
df_test= pd.DataFrame.from_dict(test_an, orient="index")
print(df_test)

        id sentence_id tok_id  head error         form1         form2  \
1    28_12          28     12        True        actual        actual
2    35_19          35     19        True  conscienciar  conscienciar
3    35_25          35     25        True   finançament   finançament
4    35_26          35     26        True           vol           vol
5    57_42          57     42        True        hivern        hivern
..     ...         ...    ...         ...           ...           ...
71   196_6         196      6        True      establir      establir
72  196_22         196     22        True           que           que
73  196_23         196     23        True       prevegi       prevegi
74  197_28         197     28        True         veïns         veïns
75  200_25         200     25        True         tenir         tenir

   righthead wronghead
1          9        11
2         15        26
3         19        26
4         19        15
5         40        38
..       ...       ...
71         4        23
72         6        23
73         6         4
74        26        24
75         6        17

[75 rows x 8 columns]

In [71]:
from read_conllu import test_annotation
test_an= test_annotation("ca_ancora-ud-train.conllu","200_ca_spacy_low.conllu",  200, "lemma", printf= False)
df_test= pd.DataFrame.from_dict(test_an)
df_test.describe()
#df_test["id"]

,1_48,3_14,4_12,7_15,12_15,15_27,16_19,16_34,18_8,19_5,...,193_14,193_31,194_11,194_23,196_23,196_32,197_28,197_37,197_47,198_28
count,8,8,8,8,8,8,8,8,8,8,...,8,8,8,8,8,8,8,8,8,8
unique,7,7,6,7,7,7,6,7,6,7,...,7,6,6,6,7,7,6,6,6,7
top,càrniques,càrniques,una,desconeguessin,es,es,la,es,una,es,...,es,quines,una,la,prevegi,possibilitin,veïns,la,la,esdevingut
freq,2,2,3,2,2,2,3,2,3,2,...,2,3,3,3,2,2,3,3,3,2

In [89]:
from read_conllu import test_annotation
test_an= test_annotation("ca_ancora-ud-train.conllu","200_ca_spacy_low.conllu",  200, "deprel", printf= False)
df_test= pd.DataFrame.from_dict(test_an, orient="index")
df_test.describe()
print(df_test)

            id sentence_id tok_id  deprel error         form1         form2  \
1_37      1_37           1     37          True       càrrecs       càrrecs
2_6        2_6           2      6          True          qual          qual
2_18      2_18           2     18          True    processats    processats
2_52      2_52           2     52          True    inspectors    inspectors
2_75      2_75           2     75          True   funcionaris   funcionaris
...        ...         ...    ...           ...           ...           ...
196_19  196_19         196     19          True   implantació   implantació
196_23  196_23         196     23          True       prevegi       prevegi
197_26  197_26         197     26          True  associacions  associacions
197_28  197_28         197     28          True         veïns         veïns
198_11  198_11         198     11          True       augment       augment

       rightdeprel wrongdeprel
1_37       obl:arg         obj
2_6        obl:arg         obj
2_18     obl:agent         obj
2_52       obl:arg         obj
2_75       obl:arg         obj
...            ...         ...
196_19     obl:arg         obj
196_23       xcomp       ccomp
197_26        nmod        flat
197_28        nmod        flat
198_11     obl:arg         obj

[143 rows x 8 columns]

In [88]:
from read_conllu import test_annotation
test_an= test_annotation("ca_ancora-ud-train.conllu","200_ca_spacy.conllu",  200, "deprel", printf= False)
df_test= pd.DataFrame.from_dict(test_an, orient="index")
df_test.describe()
print(df_test)

            id sentence_id tok_id  deprel error        form1        form2  \
1_37      1_37           1     37          True      càrrecs      càrrecs
2_6        2_6           2      6          True         qual         qual
2_18      2_18           2     18          True   processats   processats
2_52      2_52           2     52          True   inspectors   inspectors
2_65      2_65           2     65          True    Audiència    Audiència
...        ...         ...    ...           ...          ...          ...
196_6    196_6         196      6          True     establir     establir
196_19  196_19         196     19          True  implantació  implantació
196_23  196_23         196     23          True      prevegi      prevegi
198_11  198_11         198     11          True      augment      augment
200_38  200_38         200     38          True   Ajuntament   Ajuntament

       rightdeprel wrongdeprel
1_37       obl:arg         obj
2_6        obl:arg         obj
2_18     obl:agent         obj
2_52       obl:arg         obj
2_65     obl:agent         obj
...            ...         ...
196_6        ccomp         aux
196_19     obl:arg         obj
196_23       xcomp       ccomp
198_11     obl:arg         obj
200_38   obl:agent         obj

[170 rows x 8 columns]

In [4]:
from read_conllu import test_annotation
test_an= test_annotation("200_ca_spacy.conllu","200_ca_spacy_low.conllu",  200, "deprel", printf= False)
df_test_deprel= pd.DataFrame.from_dict(test_an, orient="index")
df_test_deprel.describe()

,id,sentence_id,tok_id,deprel error,form1,form2,rightdeprel,wrongdeprel
count,32,32,32,32,32,32,32,32
unique,32,27,24,1,27,27,14,11
top,15_9,64,9,True,comarcal,comarcal,amod,flat
freq,1,2,3,32,3,3,9,14

In [92]:
print(df_test_deprel)

            id sentence_id tok_id  deprel error           form1  \
15_9      15_9          15      9          True         general
52_4      52_4          52      4          True          comerç
55_18    55_18          55     18          True  estacionalitat
56_7      56_7          56      7          True          comerç
60_15    60_15          60     15          True        comarcal
61_6      61_6          61      6          True        comarcal
64_16    64_16          64     16          True           dotar
64_32    64_32          64     32          True             una
72_10    72_10          72     10          True             dur
83_6      83_6          83      6          True             són
92_20    92_20          92     20          True   metropolitana
106_14  106_14         106     14          True      implantant
122_24  122_24         122     24          True      monumental
125_9    125_9         125      9          True        inferior
131_17  131_17         131     17          True     planejament
141_50  141_50         141     50          True         empresa
141_62  141_62         141     62          True     compravenda
142_12  142_12         142     12          True        empreses
152_35  152_35         152     35          True             fer
160_7    160_7         160      7          True             una
169_8    169_8         169      8          True          social
171_34  171_34         171     34          True      instrucció
171_79  171_79         171     79          True              en
173_10  173_10         173     10          True      instrucció
177_18  177_18         177     18          True         central
182_35  182_35         182     35          True            avui
182_42  182_42         182     42          True        comarcal
187_20  187_20         187     20          True           tasca
190_9    190_9         190      9          True              hi
191_30  191_30         191     30          True              un
197_26  197_26         197     26          True    associacions
197_28  197_28         197     28          True           veïns

                 form2 rightdeprel wrongdeprel
15_9           general        amod        flat
52_4            comerç        nmod        flat
55_18   estacionalitat         obl         obj
56_7            comerç        nmod        flat
60_15         comarcal        amod        flat
61_6          comarcal        amod        flat
64_16            dotar       ccomp       xcomp
64_32              una         det      nummod
72_10              dur         aux       xcomp
83_6               són         cop          cc
92_20    metropolitana        amod        flat
106_14      implantant       advcl       xcomp
122_24      monumental        amod        flat
125_9         inferior        amod       punct
131_17     planejament         obl        nmod
141_50         empresa         obj       nsubj
141_62     compravenda         obl        nmod
142_12        empreses        conj         obj
152_35             fer         aux       xcomp
160_7              una      nummod         det
169_8           social        amod        flat
171_34      instrucció        nmod        flat
171_79              en         dep        mark
173_10      instrucció        nmod        flat
177_18         central        amod        flat
182_35            avui      advmod         obl
182_42        comarcal        amod        flat
187_20           tasca         obj         obl
190_9               hi        iobj         obj
191_30              un         det      nummod
197_26    associacions        nmod        flat
197_28           veïns        nmod        flat

In [5]:
head_dict= test_annotation("ca_ancora-ud-train.conllu","200_ca_spacy_low.conllu",  200, "lemma", printf= False)
deprel_dict= test_annotation("ca_ancora-ud-train.conllu","200_ca_spacy_low.conllu",  200, "lemma", printf= False)

In [9]:
print(head_dict.keys())
print(deprel_dict.keys())
c=0
for key in head_dict:
    if key in deprel_dict:
        print(key)
        c+=1

print(c)

dict_keys(['1_48', '3_14', '4_12', '7_15', '12_15', '15_27', '16_19', '16_34', '18_8', '19_5', '19_17', '20_3', '21_37', '32_18', '32_30', '34_12', '34_20', '37_15', '37_29', '37_30', '38_23', '43_55', '44_24', '49_33', '50_31', '51_16', '52_37', '53_4', '53_13', '55_3', '55_14', '56_15', '60_4', '60_26', '60_27', '62_10', '63_16', '63_40', '63_41', '63_44', '63_52', '64_32', '64_63', '66_18', '66_24', '67_3', '68_5', '69_10', '70_20', '72_8', '72_23', '75_26', '75_41', '78_9', '79_12', '81_23', '85_15', '87_12', '89_34', '91_7', '97_11', '98_22', '99_8', '100_49', '100_63', '103_2', '103_18', '105_3', '105_18', '105_32', '106_4', '106_10', '108_31', '109_9', '109_15', '114_12', '114_62', '117_27', '122_3', '122_13', '124_4', '124_8', '126_14', '126_15', '127_5', '128_13', '128_34', '130_27', '134_22', '135_19', '137_38', '138_10', '140_5', '142_2', '143_10', '144_7', '144_19', '146_7', '147_16', '147_38', '147_50', '148_56', '149_22', '150_23', '150_38', '151_6', '152_9', '152_34', '155_3', '159_15', '159_20', '159_44', '160_7', '160_15', '161_7', '161_37', '162_2', '162_9', '162_16', '164_22', '165_16', '171_28', '174_48', '177_10', '180_5', '180_44', '181_11', '181_33', '185_4', '187_17', '189_10', '191_23', '192_24', '192_61', '193_14', '193_31', '194_11', '194_23', '196_23', '196_32', '197_28', '197_37', '197_47', '198_28'])
dict_keys(['1_48', '3_14', '4_12', '7_15', '12_15', '15_27', '16_19', '16_34', '18_8', '19_5', '19_17', '20_3', '21_37', '32_18', '32_30', '34_12', '34_20', '37_15', '37_29', '37_30', '38_23', '43_55', '44_24', '49_33', '50_31', '51_16', '52_37', '53_4', '53_13', '55_3', '55_14', '56_15', '60_4', '60_26', '60_27', '62_10', '63_16', '63_40', '63_41', '63_44', '63_52', '64_32', '64_63', '66_18', '66_24', '67_3', '68_5', '69_10', '70_20', '72_8', '72_23', '75_26', '75_41', '78_9', '79_12', '81_23', '85_15', '87_12', '89_34', '91_7', '97_11', '98_22', '99_8', '100_49', '100_63', '103_2', '103_18', '105_3', '105_18', '105_32', '106_4', '106_10', '108_31', '109_9', '109_15', '114_12', '114_62', '117_27', '122_3', '122_13', '124_4', '124_8', '126_14', '126_15', '127_5', '128_13', '128_34', '130_27', '134_22', '135_19', '137_38', '138_10', '140_5', '142_2', '143_10', '144_7', '144_19', '146_7', '147_16', '147_38', '147_50', '148_56', '149_22', '150_23', '150_38', '151_6', '152_9', '152_34', '155_3', '159_15', '159_20', '159_44', '160_7', '160_15', '161_7', '161_37', '162_2', '162_9', '162_16', '164_22', '165_16', '171_28', '174_48', '177_10', '180_5', '180_44', '181_11', '181_33', '185_4', '187_17', '189_10', '191_23', '192_24', '192_61', '193_14', '193_31', '194_11', '194_23', '196_23', '196_32', '197_28', '197_37', '197_47', '198_28'])
1_48
3_14
4_12
7_15
12_15
15_27
16_19
16_34
18_8
19_5
19_17
20_3
21_37
32_18
32_30
34_12
34_20
37_15
37_29
37_30
38_23
43_55
44_24
49_33
50_31
51_16
52_37
53_4
53_13
55_3
55_14
56_15
60_4
60_26
60_27
62_10
63_16
63_40
63_41
63_44
63_52
64_32
64_63
66_18
66_24
67_3
68_5
69_10
70_20
72_8
72_23
75_26
75_41
78_9
79_12
81_23
85_15
87_12
89_34
91_7
97_11
98_22
99_8
100_49
100_63
103_2
103_18
105_3
105_18
105_32
106_4
106_10
108_31
109_9
109_15
114_12
114_62
117_27
122_3
122_13
124_4
124_8
126_14
126_15
127_5
128_13
128_34
130_27
134_22
135_19
137_38
138_10
140_5
142_2
143_10
144_7
144_19
146_7
147_16
147_38
147_50
148_56
149_22
150_23
150_38
151_6
152_9
152_34
155_3
159_15
159_20
159_44
160_7
160_15
161_7
161_37
162_2
162_9
162_16
164_22
165_16
171_28
174_48
177_10
180_5
180_44
181_11
181_33
185_4
187_17
189_10
191_23
192_24
192_61
193_14
193_31
194_11
194_23
196_23
196_32
197_28
197_37
197_47
198_28
144

In [2]:
15+63+16

94

In [3]:
len([])

0